name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch: # Manuelles Starten aktivieren
    inputs:
      deploy_on_server:
        description: "Production Deployment"
        required: true
        default: "false"

jobs:
  deploy:
    runs-on: ubuntu-24.04
    environment: production # Environment mit Genehmigungsregel
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        run: |
          # SSH Setup
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan 45.129.183.223 >> ~/.ssh/known_hosts

          # Ensure a clean /root/skeleton directory on the server
          ssh -i ~/.ssh/id_ed25519 root@45.129.183.223 "
            rm -rf /root/skeleton &&
            mkdir -p /root/skeleton
          "

          # Pull latest code from GitHub
          ssh -i ~/.ssh/id_ed25519 root@45.129.183.223 "
            cd /root/skeleton &&
            git clone https://github.com/michii0103/skeleton.git . &&
            npm install &&
            npm run build &&
            pm2 start ecosystem.config.cjs --env production
          "
