name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy built files to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan 45.129.183.223 >> ~/.ssh/known_hosts
          rsync -avz -e "ssh -i ~/.ssh/id_ed25519" ./dist/ root@45.129.183.223:/skeleton/dist
          ssh -i ~/.ssh/id_ed25519 root@45.129.183.223 "cd /skeleton && npm install && pm2 restart all"
